name: Prettier Lint Check
on:
  push:
  pull_request:
  repository_dispatch:

jobs:
  run-linters:
    name: Run Linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run check linters
        run: yarn prettier -c **/*.js
